-- firstdate current month
SELECT DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0) AS [AWAL BULAN]
-- lastdate previous month
SELECT DATEADD(DAY, -(DAY(GETDATE())), GETDATE()) AS [AKHIR BULAN KEMAREN]
-- lastdate current month
SELECT DATEADD (DAY, -1, DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) + 1, 0)) AS [AKHIR BULAN NANTI]
-- firstdate next month
SELECT DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) + 1, 0) AS [AWAL BULAN DEPAN]
-- firstdate current year
SELECT DATEADD(YEAR, DATEDIFF(YEAR, 0, GETDATE()), 0) AS [AWAL TAHUN]
-- lastdate current year
SELECT DATEADD(YEAR, DATEDIFF(YEAR, 0, GETDATE()) + 1, -1) AS [AKHIR TAHUN]
